### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by Fanboyx** [D4edalus/CoD4x_Server#51]
Hi hoo,
since i installed cod4x i cant play anymore. If i try to join a server the connection-timer counts to 10 and i get a connection error.  And pls dont tell me to set the timer to 60 oder higher. If I do this, it counts to 60 and i get the error again.
Is this a general cod4x problem? Btw Im using steam.

greets

**Comment by bykidi** [comment]
i fixed this on my side by allowing connections to cod4x.me

**Comment by D4edalus** [comment]
I havent heared of that problem yet. I would assume that your network
configuration is blocking the traffic somewhere as our servers are running
fine.

Can you describe in more detail for what server that problem occurs?

Am 25.08.2016 1:08 vorm. schrieb "bykidi" <notifications@github.com>:

i fixed this on my side by allowing connections to cod4x.me

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/D4edalus/CoD4x_Server/issues/51#issuecomment-242236145>,
or mute the thread

**Comment by IceNinjaman** [comment]
This is kinda nonsense as we host not a single service you need to join a server. The only thing you miss is our serverlist and the updater. I can not understand this.

**Comment by Fanboyx** [comment]
The Problem appeared right after updating to 1.8. For me it looked like there was a relation.

How did you allowe the connection to cod4x.me? There is nothing blocked?!

**Comment by T-Maxxx** [comment]
Firewall mostly. Windows one or antivirus. You should allow incoming UDP traffic for game and for `insert cod4x.me master server ip:port here`.
When you asks server to allow connection, you send auth packets to server and to master server. Then game server sends another packet to master server where it asks "Is this user legit?". If your game auth packet didn't delivered to master before, the response will be "No" => server will ignore any packets from you until next "connect" packet. OR your firewall just blocked UDP traffic for iw3mp.exe => no "connectResponse" packet from server => connection timeout.

**Comment by IceNinjaman** [comment]
Do you receive the in game server list?

**Comment by IceNinjaman** [comment]
T-Max reply is valid for cod4 1.7 servers. If you going to join non cracked 1.7 server you indeed need connection to Activision master server.
However it more likely seems to be a non bound socket. That why I want to know if you receive in game serverlists when using the serverbrowser.

**Comment by D4edalus** [comment]
since no further reply was given and a new client release has happened in between, we assume the problem to be solved
