### ISSUE TITLE
About patching WeaponDef XAsset and precaching

### ISSUE THREAD

**Issue by T-Maxxx** [D4edalus/CoD4x_Server#55]
As I can see, there is no reallocation for items (aka *WeaponDef* xassets). But during RE configstring types I have found few functions where used limit to 128 items so If you have patched xasset up to, for example, 256 items - precache will not work and game will throw "item not precached" errors.
I know, that's a common problem for many mods when you can't get more than 128 weapons at the time and it'll be great to see that reallocation. As I know, in usercmds there's field called "byte weapon" so looks like its ok to increase limit to 256.
Also there's a lot of xrefs to [these arrays](https://gist.github.com/T-Maxxx/d65bf998e4111fde3a581244dae8ca09) and that's the reason why there's no allocations for now?

**Comment by IceNinjaman** [comment]
I know about the weapon asset issue. Well there are a shit load of references and arrays involved into it. I have patched in iw3mp.exe around 300 base offsets I believe. Now there are also arrays with 128 entries in playerState_t struct. you can hardly expand them here. You need some kind of compression I think. Anyway because I would have to do that time consuming patching on the server side program as  well I kinda gave up with it. You can only load 128 weapon assets and that is it atm.
