### ISSUE TITLE
Screenshot Details

### ISSUE THREAD

**Issue by utakerkhan** [D4edalus/CoD4x_Server#58]
More screenshot details should be added in exif jpg, like following:
- Client IP
I know some have concern about privacy for server admins and their users since some server admins have publically listed screenshots in real time,  so control this saving info by a dvar which by default is off, like
sv_saveIPinSS 0 and let the server owner decide if it needs to be enabled.

**Comment by IceNinjaman** [comment]
Won't happen I assume because admins list them in public and care a fuck about users privacy.

**Comment by IceNinjaman** [comment]
Also the ip address is usually not so helpful for identifying an unique player. That your GamingLongue IP addresses are some VPN ip addresses you can assign to each user uniquely is a special case. Why do you have even so many IP addresses in 2016?

**Comment by utakerkhan** [comment]
let server owners decide plz, if its disabled by default so everyone won't be enabling it.

**Comment by T-Maxxx** [comment]
I think GUID/SteamID will be enough. Its harder to change than IP since its UDP.

**Comment by efinst0rm** [comment]
+ 1 Please add Username & GUID/SteamID to the screen shots.

**Comment by IceNinjaman** [comment]
I believe this is already inside there stored.

**Comment by Kingwolf123** [comment]
If Screenshot details are going to be implemented, Just add the PlayerID/Steam ID of the player on the screenshot. IP Address wont be of much use since they are dynamic, so adding them would not be helpful in this context. I think exposing PlayerID/Steam ID wont be as much of a security concern as exposing the ip-address of clients. 
Making a Dvar for listing the PlayerID/SteamID would be unecassary work, just implement it as default in the screenshot.
@utakerkhan Server owners can only decide on the features that are made available by Cod4X developers and can only request features to be implemented. Rest is up to developers as to how they want to approach it since they know better than us. Server Owners cannot decide or tell Cod4x Developers what to do. You can always implement the feature yourself if you need it that badly.

**Comment by IceNinjaman** [comment]
Well its a custom header on the very end of screenshot files. Writing on images is not so smart.

**Comment by T-Maxxx** [comment]
... and will require additional lib dependencies unless you want to create your own jpeg editor. A bit of uploading logic (like getting name\guid from file path) will be much easier but no one says being an admin its easy job.

**Comment by florczakraf** [comment]
I have another question regarding screenshots so I will hook up to this
thread. Would it be possible to have lossless format for screenshots?
(Preferably png.)
You may ask: why?
The answer is that a lot of people use low resolutions (that number
surprises me a lot) which along the jpeg compression make those screenshots
pointless to watch. Example: http://i.imgur.com/h9t9HKs.jpg

**Comment by D4edalus** [comment]
@T-Maxxx you could just use the Plugin callback i created yesterday to store away details to a screenshot into a database including a reference to the filename

**Comment by IceNinjaman** [comment]
Lossless format is far too large. PNG is not a lossless format. And the JPG quality is so bad because its compressed a lot to make the files small. I am kinda aware of this issue that why I have already increased the jpeg quality when less than 1.000.000 pixels going to be stored. This is part of the 16.0 update.

**Comment by D4edalus** [comment]
Png is lossless. From what i have seen JPEG is fine, just depends on the
level of compression

Am 06.09.2016 11:51 nachm. schrieb "IceNinjaman" <notifications@github.com>:

**Comment by utakerkhan** [comment]
jpg is pretty good enough, many ppl playing cod4 client have adsl which has limited upload bandwidth so maybe decreasing quality of jpg will be better but dont changes format plz; we've observed connection interruption on slow speed users
as for added info, jpb header exist if fine by default make it dvar configurable, besides other anti cheats also get lots more detail, i've just asked for owner conscent configuration
