### ISSUE TITLE
Wrong repo but yeah. Linux & mac client patch?

### ISSUE THREAD

**Issue by AoKMiKeY** [D4edalus/CoD4x_Server#7]
Would be great to have the client patch made compatible for these two systems. I would be happy to help test.

**Comment by T-Maxxx** [comment]
I think it never will be released because of ingame rendering system (there is no d3dx routines available. At least for Linux). Use Wine or its analogue on MacOS to launch game on this OSs.

**Comment by D4edalus** [comment]
Since by far not all parts of the client are even reversed, including parts of the rendering system, it is not possible to port the client to other systems without unreal effort.
If I'd have the full sourcecode I would happily write an Opengl rendering system for it. But under the current circumstances that won't happen. 

The amount of gamers on Linux is a neglectable minorty of ~0.3% according to Steam. It is a pitty that we loose the MacOs playerbase altough it is also very small with ~3.5%. Talking about being interested and doing actual work are pretty far from each other. 

Opensourcing of the client by us won't happen. Even releasing it with a closed anti-cheat module is far from realistic. You only have to think about how a hacker can compile his own client and just modify dvars. Furthermore a hacker wouldn't be needed to make sense of the assembly code to reverse and change parts of the client, he'd be just able to flip some bits in readable C code.
This goes as far as that a changed binary structure of the client would make it way harder to detect known hacks. I won't go into further detail as I don't wanna disclose our methods.

The only realistic scenario where I can see an open source client happening is if the respective IW engine version would be opensourced by ATVI.

**Comment by AoKMiKeY** [comment]
@D4edalus Thank you for getting back to my issue. I understand why its not on the OS's now. Thanks.
